{% set name = "kaggle-environments" %}
{% set version = "1.14.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kaggle-environments-{{ version }}.tar.gz
  sha256: 7044d1cd64657a7c3f342d65ca4388e1648871e63deb4be9c425d0d996cf7984

build:
  number: 1
  noarch: python
  entry_points:
    - kaggle-environments = kaggle_environments.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - flask >=1.1.2
    - gym
    - ipython
    - jsonschema >=3.0.1
    - numpy >=1.19.5
    - python >={{ python_min }}
    - requests >=2.25.1

test:
  imports:
    - kaggle_environments
  commands:
    - pip check
    - kaggle-environments --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kaggle/kaggle-environments
  summary: Kaggle Environments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
