{% set name = "kaggle-environments" %}
{% set version = "1.16.2" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kaggle-environments-{{ version }}.tar.gz
  sha256: e7e0436e03e3d04a198b0fc9dcd332a8228c51e0d7e17971fb8da07744bf6f05

build:
  number: 0
  noarch: python
  entry_points:
    - kaggle-environments = kaggle_environments.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - flask >=1.1.2
    - gym
    - ipython
    - jsonschema >=3.0.1
    - numpy >=1.19.5
    - python >={{ python_min }}
    - requests >=2.25.1
    - gymnasium=0.28.0
    - pettingzoo 1.24.*
    - scipy
    - shimmy
    - stable-baselines3=2.1.0
    - transformers
    - chessnut

test:
  imports:
    - kaggle_environments
  commands:
    - pip check
    - kaggle-environments --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Kaggle/kaggle-environments
  summary: Kaggle Environments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
