{% set name = "kaggle-environments" %}
{% set version = "1.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kaggle-environments-{{ version }}.tar.gz
  sha256: c35d791d3e0c466fe7357ab177638d3c1e239cb65d6e02313282a991ec3501ac

build:
  number: 0
  noarch: python
  entry_points:
    - kaggle-environments = kaggle_environments.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask >=1.1.2
    - gym
    - ipython
    - jsonschema >=3.0.1
    - numpy >=1.19.5
    - python >=3.6
    - requests >=2.25.1

test:
  imports:
    - kaggle_environments
  commands:
    - pip check
    - kaggle-environments --help
  requires:
    - pip

about:
  home: https://github.com/Kaggle/kaggle-environments
  summary: Kaggle Environments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
